# llm_driving/vector_prefix_t5.py

"""
VectorPrefixT5: wraps a T5ForConditionalGeneration model with a
VectorPrefixEncoder so that learned vector embeddings are prepended
to the T5 encoder input as prefix tokens.

Stage 1 usage:
    Input:  vectors (B, MAX_OBJECTS, 8) + text prompt tokens
    Output: caption text (generated by T5 decoder)

The vector encoder produces (B, PREFIX_LEN, d_model) prefix embeddings.
These are concatenated with the text token embeddings before entering
the T5 encoder, giving the model a learned numeric representation
alongside (or instead of) the text-serialized vectors.
"""

from __future__ import annotations
import json
import os
import logging
from dataclasses import asdict
from typing import Optional

import torch
import torch.nn as nn
from transformers import AutoModelForSeq2SeqLM
from transformers.modeling_outputs import BaseModelOutput, Seq2SeqLMOutput

from .vector_encoder import VectorPrefixEncoder, VectorEncoderConfig

logger = logging.getLogger("llm_driving")


class VectorPrefixT5(nn.Module):
    """
    Composite model: VectorPrefixEncoder + T5ForConditionalGeneration.

    During forward(), vector prefix embeddings are prepended to the
    T5 encoder's word embeddings, and the attention mask is extended
    accordingly.
    """

    def __init__(self, t5_model, vector_encoder: VectorPrefixEncoder):
        super().__init__()
        self.t5 = t5_model
        self.vector_encoder = vector_encoder
        # Expose config for HF Trainer compatibility
        self.config = t5_model.config

    # ------------------------------------------------------------------
    # Core: build prefix + text embeddings, run T5 encoder
    # ------------------------------------------------------------------

    def _build_encoder_inputs(
        self,
        input_ids: torch.Tensor,
        attention_mask: torch.Tensor,
        vectors: torch.Tensor,
        num_objects: torch.Tensor,
    ):
        """
        Returns:
            encoder_embeds: (B, P+T, d_model)
            full_mask:      (B, P+T)
        """
        # Prefix embeddings from vector encoder
        prefix_embeds = self.vector_encoder(vectors, num_objects)  # (B, P, d_model)

        # Text embeddings from T5 encoder's embedding layer
        text_embeds = self.t5.encoder.embed_tokens(input_ids)  # (B, T, d_model)

        # Concatenate: [prefix ; text]
        encoder_embeds = torch.cat([prefix_embeds, text_embeds], dim=1)  # (B, P+T, d_model)

        # Extend attention mask for prefix positions (all valid)
        B, P = prefix_embeds.shape[:2]
        prefix_mask = torch.ones(
            B, P, device=attention_mask.device, dtype=attention_mask.dtype
        )
        full_mask = torch.cat([prefix_mask, attention_mask], dim=1)  # (B, P+T)

        return encoder_embeds, full_mask

    # ------------------------------------------------------------------
    # Forward (training)
    # ------------------------------------------------------------------

    def forward(
        self,
        input_ids: torch.Tensor,
        attention_mask: torch.Tensor,
        labels: Optional[torch.Tensor] = None,
        vectors: Optional[torch.Tensor] = None,
        num_objects: Optional[torch.Tensor] = None,
        **kwargs,
    ) -> Seq2SeqLMOutput:
        """
        Training forward pass.

        If vectors/num_objects are provided, builds prefix embeddings
        and prepends them. Otherwise falls back to standard T5 forward.
        """
        if vectors is not None and num_objects is not None:
            encoder_embeds, full_mask = self._build_encoder_inputs(
                input_ids, attention_mask, vectors, num_objects
            )

            # Run T5 encoder with inputs_embeds (bypasses embed_tokens)
            encoder_outputs = self.t5.encoder(
                inputs_embeds=encoder_embeds,
                attention_mask=full_mask,
            )

            # Run full model with precomputed encoder outputs
            outputs = self.t5(
                encoder_outputs=encoder_outputs,
                attention_mask=full_mask,
                labels=labels,
            )
        else:
            # Fallback: standard text-only forward
            outputs = self.t5(
                input_ids=input_ids,
                attention_mask=attention_mask,
                labels=labels,
            )

        return outputs

    # ------------------------------------------------------------------
    # Generate (inference)
    # ------------------------------------------------------------------

    @torch.no_grad()
    def generate(
        self,
        input_ids: torch.Tensor,
        attention_mask: torch.Tensor,
        vectors: torch.Tensor,
        num_objects: torch.Tensor,
        **gen_kwargs,
    ) -> torch.Tensor:
        """
        Generate text with vector prefix embeddings.
        """
        encoder_embeds, full_mask = self._build_encoder_inputs(
            input_ids, attention_mask, vectors, num_objects
        )

        # Run T5 encoder
        encoder_out = self.t5.encoder(
            inputs_embeds=encoder_embeds,
            attention_mask=full_mask,
        )

        # Wrap in BaseModelOutput for generate() compatibility
        encoder_outputs = BaseModelOutput(
            last_hidden_state=encoder_out.last_hidden_state,
        )

        # Generate using precomputed encoder outputs
        return self.t5.generate(
            encoder_outputs=encoder_outputs,
            attention_mask=full_mask,
            **gen_kwargs,
        )

    # ------------------------------------------------------------------
    # Save / Load
    # ------------------------------------------------------------------

    def save_pretrained(self, output_dir: str):
        """
        Save both the T5 model and vector encoder to output_dir.
        """
        os.makedirs(output_dir, exist_ok=True)

        # Save T5 model weights + config
        self.t5.save_pretrained(output_dir)

        # Save vector encoder state dict
        vec_enc_path = os.path.join(output_dir, "vector_encoder.pt")
        torch.save(self.vector_encoder.state_dict(), vec_enc_path)

        # Save vector encoder config
        vec_cfg_path = os.path.join(output_dir, "vector_encoder_config.json")
        with open(vec_cfg_path, "w") as f:
            json.dump(asdict(self.vector_encoder.cfg), f, indent=2)

        logger.info(f"[VectorPrefixT5] Saved to {output_dir}")

    @classmethod
    def from_pretrained(cls, model_dir: str, device: str = "cpu") -> "VectorPrefixT5":
        """
        Load a VectorPrefixT5 from a saved directory.
        """
        # Load vector encoder config
        vec_cfg_path = os.path.join(model_dir, "vector_encoder_config.json")
        with open(vec_cfg_path, "r") as f:
            cfg_dict = json.load(f)
        vec_cfg = VectorEncoderConfig(**cfg_dict)

        # Load T5 model
        t5_model = AutoModelForSeq2SeqLM.from_pretrained(model_dir, local_files_only=True)

        # Load vector encoder
        vector_encoder = VectorPrefixEncoder(vec_cfg)
        vec_enc_path = os.path.join(model_dir, "vector_encoder.pt")
        vector_encoder.load_state_dict(
            torch.load(vec_enc_path, map_location=device, weights_only=True)
        )

        model = cls(t5_model, vector_encoder)
        model.to(device)
        logger.info(f"[VectorPrefixT5] Loaded from {model_dir}")
        return model

    # ------------------------------------------------------------------
    # Convenience: device / dtype forwarding
    # ------------------------------------------------------------------

    @property
    def device(self):
        return next(self.t5.parameters()).device

    def to(self, *args, **kwargs):
        self.t5 = self.t5.to(*args, **kwargs)
        self.vector_encoder = self.vector_encoder.to(*args, **kwargs)
        return self
